/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param comments 
 * @param followers 
 * @param invites 
 */

data class AccountSettingsEmailGet200Response (

    @Json(name = "comments")
    val comments: kotlin.Boolean? = null,

    @Json(name = "followers")
    val followers: kotlin.Boolean? = null,

    @Json(name = "invites")
    val invites: kotlin.Boolean? = null

)

