/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CalendarEntry

import com.squareup.moshi.Json

/**
 * 
 *
 * @param older 
 * @param newer 
 * @param id 
 */

data class AdjacentEntries (

    @Json(name = "older")
    val older: CalendarEntry? = null,

    @Json(name = "newer")
    val newer: CalendarEntry? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null

)

