/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param invite 
 * @param vote 
 * @param comment 
 * @param live 
 */

data class AuthProfileAllOfBan (

    @Json(name = "invite")
    val invite: kotlin.Double? = null,

    @Json(name = "vote")
    val vote: kotlin.Double? = null,

    @Json(name = "comment")
    val comment: kotlin.Double? = null,

    @Json(name = "live")
    val live: kotlin.Double? = null

)

