/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuthProfileAllOfAccount
import org.openapitools.client.models.AuthProfileAllOfBan

import com.squareup.moshi.Json

/**
 * 
 *
 * @param birthday 
 * @param showInTops 
 * @param account 
 * @param ban 
 */

data class AuthProfileAllOf (

    @Json(name = "birthday")
    val birthday: kotlin.String? = null,

    @Json(name = "showInTops")
    val showInTops: kotlin.Boolean? = null,

    @Json(name = "account")
    val account: AuthProfileAllOfAccount? = null,

    @Json(name = "ban")
    val ban: AuthProfileAllOfBan? = null

)

