/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CalendarEntry

import com.squareup.moshi.Json

/**
 * 
 *
 * @param propertyEntries 
 * @param start 
 * @param end 
 * @param limit 
 */

data class Calendar (

    @Json(name = "entries")
    val propertyEntries: kotlin.collections.List<CalendarEntry>? = null,

    @Json(name = "start")
    val start: java.math.BigDecimal? = null,

    @Json(name = "end")
    val end: java.math.BigDecimal? = null,

    @Json(name = "limit")
    val limit: kotlin.Int? = null

)

