/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatRights
import org.openapitools.client.models.Message
import org.openapitools.client.models.User

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param partner 
 * @param lastMessage 
 * @param unreadCount 
 * @param rights 
 */

data class Chat (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "partner")
    val partner: User? = null,

    @Json(name = "lastMessage")
    val lastMessage: Message? = null,

    @Json(name = "unreadCount")
    val unreadCount: kotlin.Int? = null,

    @Json(name = "rights")
    val rights: ChatRights? = null

)

