/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Comment

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `data` 
 * @param nextAfter 
 * @param hasAfter 
 * @param nextBefore 
 * @param hasBefore 
 */

data class CommentList (

    @Json(name = "data")
    val `data`: kotlin.collections.List<Comment>? = null,

    @Json(name = "nextAfter")
    val nextAfter: kotlin.String? = null,

    @Json(name = "hasAfter")
    val hasAfter: kotlin.Boolean? = null,

    @Json(name = "nextBefore")
    val nextBefore: kotlin.String? = null,

    @Json(name = "hasBefore")
    val hasBefore: kotlin.Boolean? = null

)

