/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id user id
 * @param x1920 
 * @param x318 
 */

data class Cover (

    /* user id */
    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "x1920")
    val x1920: kotlin.String? = null,

    @Json(name = "x318")
    val x318: kotlin.String? = null

)

