/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param css 
 * @param backgroundColor color in rgb
 * @param textColor color in rgb
 * @param fontFamily 
 * @param fontSize 
 * @param textAlignment 
 */

data class Design (

    @Json(name = "css")
    val css: kotlin.String? = null,

    /* color in rgb */
    @Json(name = "backgroundColor")
    val backgroundColor: kotlin.String? = null,

    /* color in rgb */
    @Json(name = "textColor")
    val textColor: kotlin.String? = null,

    @Json(name = "fontFamily")
    val fontFamily: kotlin.String? = null,

    @Json(name = "fontSize")
    val fontSize: kotlin.Int? = null,

    @Json(name = "textAlignment")
    val textAlignment: Design.TextAlignment? = null

) {

    /**
     * 
     *
     * Values: left,right,center,justify
     */
    enum class TextAlignment(val value: kotlin.String) {
        @Json(name = "left") left("left"),
        @Json(name = "right") right("right"),
        @Json(name = "center") center("center"),
        @Json(name = "justify") justify("justify");
    }
}

