/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Friend
import org.openapitools.client.models.User

import com.squareup.moshi.Json

/**
 * 
 *
 * @param subject 
 * @param relation 
 * @param users 
 * @param nextAfter 
 * @param hasAfter 
 * @param nextBefore 
 * @param hasBefore 
 */

data class FriendList (

    @Json(name = "subject")
    val subject: User? = null,

    @Json(name = "relation")
    val relation: FriendList.Relation? = null,

    @Json(name = "users")
    val users: kotlin.collections.List<Friend>? = null,

    @Json(name = "nextAfter")
    val nextAfter: kotlin.String? = null,

    @Json(name = "hasAfter")
    val hasAfter: kotlin.Boolean? = null,

    @Json(name = "nextBefore")
    val nextBefore: kotlin.String? = null,

    @Json(name = "hasBefore")
    val hasBefore: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: followers,followings,requested,ignored,hidden,invited
     */
    enum class Relation(val value: kotlin.String) {
        @Json(name = "followers") followers("followers"),
        @Json(name = "followings") followings("followings"),
        @Json(name = "requested") requested("requested"),
        @Json(name = "ignored") ignored("ignored"),
        @Json(name = "hidden") hidden("hidden"),
        @Json(name = "invited") invited("invited");
    }
}

