/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param accessToken 
 * @param tokenType 
 * @param expiresIn 
 * @param refreshToken 
 * @param scope 
 */

data class OAuth2Token (

    @Json(name = "access_token")
    val accessToken: kotlin.String? = null,

    @Json(name = "token_type")
    val tokenType: OAuth2Token.TokenType? = null,

    @Json(name = "expires_in")
    val expiresIn: kotlin.Long? = null,

    @Json(name = "refresh_token")
    val refreshToken: kotlin.String? = null,

    @Json(name = "scope")
    val scope: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: bearer
     */
    enum class TokenType(val value: kotlin.String) {
        @Json(name = "bearer") bearer("bearer");
    }
}

