/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param error 
 */

data class OAuth2Error (

    @Json(name = "error")
    val error: OAuth2Error.Error? = null

) {

    /**
     * 
     *
     * Values: accessDenied,invalidClient,invalidGrant,invalidRedirect,invalidRequest,invalidScope,invalidToken,serverError,temporarilyUnavailable,unauthorizedClient,unrecognizedClient,unsupportedGrantType,unsupportedResponseType
     */
    enum class Error(val value: kotlin.String) {
        @Json(name = "access_denied") accessDenied("access_denied"),
        @Json(name = "invalid_client") invalidClient("invalid_client"),
        @Json(name = "invalid_grant") invalidGrant("invalid_grant"),
        @Json(name = "invalid_redirect") invalidRedirect("invalid_redirect"),
        @Json(name = "invalid_request") invalidRequest("invalid_request"),
        @Json(name = "invalid_scope") invalidScope("invalid_scope"),
        @Json(name = "invalid_token") invalidToken("invalid_token"),
        @Json(name = "server_error") serverError("server_error"),
        @Json(name = "temporarily_unavailable") temporarilyUnavailable("temporarily_unavailable"),
        @Json(name = "unauthorized_client") unauthorizedClient("unauthorized_client"),
        @Json(name = "unrecognized_client") unrecognizedClient("unrecognized_client"),
        @Json(name = "unsupported_grant_type") unsupportedGrantType("unsupported_grant_type"),
        @Json(name = "unsupported_response_type") unsupportedResponseType("unsupported_response_type");
    }
}

