/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param isOpenForMe 
 * @param toMe 
 * @param fromMe 
 */

data class ProfileAllOfRelations (

    @Json(name = "isOpenForMe")
    val isOpenForMe: kotlin.Boolean? = null,

    @Json(name = "toMe")
    val toMe: ProfileAllOfRelations.ToMe? = null,

    @Json(name = "fromMe")
    val fromMe: ProfileAllOfRelations.FromMe? = null

) {

    /**
     * 
     *
     * Values: followed,requested,ignored,hidden,none
     */
    enum class ToMe(val value: kotlin.String) {
        @Json(name = "followed") followed("followed"),
        @Json(name = "requested") requested("requested"),
        @Json(name = "ignored") ignored("ignored"),
        @Json(name = "hidden") hidden("hidden"),
        @Json(name = "none") none("none");
    }
    /**
     * 
     *
     * Values: followed,requested,ignored,hidden,none
     */
    enum class FromMe(val value: kotlin.String) {
        @Json(name = "followed") followed("followed"),
        @Json(name = "requested") requested("requested"),
        @Json(name = "ignored") ignored("ignored"),
        @Json(name = "hidden") hidden("hidden"),
        @Json(name = "none") none("none");
    }
}

