/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param from 
 * @param to 
 * @param relation 
 */

data class Relationship (

    @Json(name = "from")
    val from: kotlin.String? = null,

    @Json(name = "to")
    val to: kotlin.String? = null,

    @Json(name = "relation")
    val relation: Relationship.Relation? = null

) {

    /**
     * 
     *
     * Values: followed,requested,ignored,hidden,none
     */
    enum class Relation(val value: kotlin.String) {
        @Json(name = "followed") followed("followed"),
        @Json(name = "requested") requested("requested"),
        @Json(name = "ignored") ignored("ignored"),
        @Json(name = "hidden") hidden("hidden"),
        @Json(name = "none") none("none");
    }
}

