/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserIDBan

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param negKarma 
 * @param followersCount 
 * @param isInvited 
 * @param verified 
 * @param authority 
 * @param ban 
 */

data class UserID (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "negKarma")
    val negKarma: kotlin.Boolean? = null,

    @Json(name = "followersCount")
    val followersCount: kotlin.Long? = null,

    @Json(name = "isInvited")
    val isInvited: kotlin.Boolean? = null,

    @Json(name = "verified")
    val verified: kotlin.Boolean? = null,

    @Json(name = "authority")
    val authority: UserID.Authority? = null,

    @Json(name = "ban")
    val ban: UserIDBan? = null

) {

    /**
     * 
     *
     * Values: user,admin
     */
    enum class Authority(val value: kotlin.String) {
        @Json(name = "user") user("user"),
        @Json(name = "admin") admin("admin");
    }
}

