/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Avatar

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param showName 
 * @param isOnline 
 * @param avatar 
 */

data class User (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "showName")
    val showName: kotlin.String? = null,

    @Json(name = "isOnline")
    val isOnline: kotlin.Boolean? = null,

    @Json(name = "avatar")
    val avatar: Avatar? = null

)

