/**
 * Mindwell
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Friend

import com.squareup.moshi.Json

/**
 * 
 *
 * @param top 
 * @param query 
 * @param users 
 */

data class UsersGet200Response (

    @Json(name = "top")
    val top: kotlin.String? = null,

    @Json(name = "query")
    val query: kotlin.String? = null,

    @Json(name = "users")
    val users: kotlin.collections.List<Friend>? = null

)

